### ISSUE TITLE
Request for information on the dataset

### ISSUE THREAD

**Issue by Moumena19** [x4dx65/SpeedReader#1]
Hello,

I am trying to use your classifier. It seems that the dataset is not included. I would appreciate if someone can inform me from where to get the dataset which matches the labels.csv included in the project. Any other suggestion would also be appreciated.

Kind Regards,
Moumena.

**Comment by x4dx65** [comment]
Hi Moumena, 

Apologies for the delayed response. 
The repo has moved to brave's github and the dataset is available at: https://github.com/brave-experiments/speedreader-paper-materials
